title: Home
sidebar:
  date: true
  dateFormat: dddd, MMMM Do
  clock: false
  digitalClock: true
  twelveHourVersion: true
  period: true
  hideHassSidebar: false
  hideTopMenu: false
  showTopMenuOnMobile: true
  width:
    mobile: 0
    tablet: 25
    desktop: 18.5
  breakpoints:
    mobile: 768
    tablet: 1024
  sidebarMenu:
    - action: navigate
      navigation_path: /dashboard-test/home
      name: Home
      active: true
      icon: mdi:home
    - action: navigate
      navigation_path: /dashboard-test/google
      name: Google
      active: true
      icon: mdi:google
    - action: navigate
      navigation_path: /dashboard-test/lights
      name: Lights
      active: true
      icon: mdi:lightbulb
    - action: navigate
      navigation_path: /dashboard-test/1st-floor
      name: 1st Floor
      active: true
      icon: mdi:floor-plan
    - action: navigate
      navigation_path: /dashboard-test/2nd-floor
      name: 2nd Floor
      active: true
      icon: mdi:stairs-up
    - action: navigate
      navigation_path: /dashboard-test/cameras
      name: Cameras
      active: true
      icon: mdi:cctv
    - action: navigate
      navigation_path: /dashboard-test/media
      name: Media
      active: true
      icon: mdi:television-play
    - action: navigate
      navigation_path: /dashboard-test/xmas
      name: Xmas Lights
      active: true
      icon: mdi:pine-tree
    - action: navigate
      navigation_path: /sidebar-test/it
      name: Admin/IT
      active: true
      icon: mdi:desktop-classic
  template: |
    <li>
      {% if now().hour  < 5 %} Good night, {{ user }} {{'\U0001F634'}}
      {% elif now().hour < 12 %} Good morning, {{ user }} {{'\u2615\uFE0F'}}
      {% elif now().hour < 18 %} Good afternoon, {{ user }} {{'\U0001F44B\U0001F3FB'}}
      {% else %} Good evening, {{ user }} {{'\U0001F44B\U0001F3FB'}}{% endif %}
    </li> <li>
      {% if expand(states.light)|
         selectattr('state','eq','on')|
         rejectattr('attributes.type','eq','browser_mod' )|rejectattr('attributes.friendly_name','search','Under') | list | count
       == 1 %}
        There is a light on
       {% elif expand(states.light)|
         selectattr('state','eq','on')|
         rejectattr('attributes.type','eq','browser_mod' )|rejectattr('attributes.friendly_name','search','Under') | list | count
       > 1 %}
        There are {{ expand(states.light)|
        selectattr('state','eq','on')|
        rejectattr('attributes.type','eq','browser_mod' )|rejectattr('attributes.friendly_name','search','Under') | list | count
         }} lights on
       {% else %}
        All lights are off
      {% endif %}
    </li>
  bottomCard:
    type: custom:layout-card
    layout_type: custom:vertical-layout
    layout:
      max_cols: 1
    cardStyle: |
      :host {
        width: 100% !important;
        position: absolute;
        bottom: 0%;
        left: 0%; 
      }
      .column.cards {
        max-width: 100% !important;
      }
      .cards > :last-child {
        margin: 0px !important;
      }
    cardOptions:
      cards:
        - type: custom:simple-weather-card
          backdrop: false
          entity: weather.openweathermap
          name: ' '
          tap_action:
            action: navigate
            navigation_path: /lovelace/meteo
          style: |
            ha-card {
              background: none  !important;
              box-shadow: none !important;
              padding: 0 !important;
              margin: 4px;
              font-size: 1vw;
            }        
        - type: custom:mini-graph-card
          tap_action:
            action: none
          show:
            icon: false
            legend: false
            name: false
          entities:
            - sensor.openweathermap_temperature
          font_size: 35
          update_interval: 15
          font_size_header: 9
          hours_to_show: 24
          points_per_hour: 1
          icon: mdi:home-thermometer-outline
          color_thresholds:
            - color: '#4dd2ff'
              value: 0
            - color: '#ffa31a'
              value: 20
            - color: '#ff1a1a'
              value: 0
          style: |
            ha-card, ha-card > div {
              padding: 0px !important;

            }
            ha-card > .header.flex > div, ha-card > .states.flex > div {
              padding: 5px !important;
              font-weight: 500;
            } 
            ha-card > .info.flex > .info__item > .info__item__time {
              display: none;
            }
            ha-card {
              background-color: rgba(40,40,40,0);
            }
            .name > span {
              font-weight: 500 !important;
            }
views:
  - path: home
    title: Home
    cards:
      - type: entities
        entities:
          - person.falco1717
      - type: grid
        square: false
        columns: 1
        cards:
          - type: media-control
            entity: media_player.all
          - type: media-control
            entity: media_player.command_center_speaker_2
          - type: media-control
            entity: media_player.guest_bedroom_speaker
          - type: media-control
            entity: media_player.hallway_speaker
          - type: media-control
            entity: media_player.kitchen_display
          - type: media-control
            entity: media_player.living_room_tv
          - type: media-control
            entity: media_player.main_floor
          - type: media-control
            entity: media_player.master_bathroom_speaker
          - type: media-control
            entity: media_player.master_bedroom
          - type: media-control
            entity: media_player.master_bedroom_speaker
          - type: media-control
            entity: media_player.party
          - type: media-control
            entity: media_player.theater_tv
          - type: media-control
            entity: media_player.upstairs
      - type: entities
        entities:
          - sensor.hacs
        title: Sensor
      - type: entities
        entities:
          - entity: sensor.sun_next_dawn
            name: Next dawn
          - entity: sensor.sun_next_dusk
            name: Next dusk
          - entity: sensor.sun_next_midnight
            name: Next midnight
          - entity: sensor.sun_next_noon
            name: Next noon
          - entity: sensor.sun_next_rising
            name: Next rising
          - entity: sensor.sun_next_setting
            name: Next setting
        title: Sun
  - title: Google
    path: google
    icon: mdi:google
    layout:
      margin: 0
      gridrows: auto
      grid-template-columns: repeat(4, 1fr) 0
      grid-template-rows: 0 repeat(2, fit-content(100%)) 0fr
      grid-template-areas: |
        "sidebar  .           .       .       ."
        "sidebar  Master      Living  Office  ."
        "sidebar  Kitchen     Rachel  Guest   ."
        "sidebar  footer      footer  footer  ."
    type: custom:grid-layout
    badges: []
    cards:
      - square: false
        type: grid
        title: Master Bedroom
        cards:
          - show_name: true
            show_icon: true
            type: light
            tap_action:
              action: toggle
            entity: light.master_bedroom_lights
          - type: light
            entity: light.master_lamps
          - type: light
            entity: light.ceiling_lights
          - type: media-control
            entity: media_player.master_bedroom
        columns: 2
        view_layout:
          grid-area: Master
      - square: false
        type: grid
        title: Living Room
        cards:
          - type: light
            entity: light.living_room_lights
          - type: media-control
            entity: media_player.living_room_tv
          - type: vertical-stack
            cards:
              - type: weather-forecast
                entity: weather.openweathermap
        columns: 2
        view_layout:
          grid-area: Living
      - type: custom:layout-card
        column_num: 2
        max_columns: 2
        column_width:
          - 35%
          - 65%
        layout: vertical
        cards:
          - type: markdown
            title: TP-Link TL-WDR3600 Router
            content: ' '
          - type: horizontal-stack
            cards:
              - type: glance
                title: Sent
                columns: 1
                entities:
                  - entity: sensor.wireless_router_tl_wdr3600_kbyte_sec_sent
                    name: Kilobytes/second
                  - entity: sensor.wireless_router_tl_wdr3600_bytes_sent
                    name: Total Bytes
                  - entity: sensor.wireless_router_tl_wdr3600_packets_sec_sent
                    name: Packets/second
                  - entity: sensor.wireless_router_tl_wdr3600_packets_sent
                    name: Total Packets
              - type: glance
                columns: 1
                title: Received
                entities:
                  - entity: sensor.wireless_router_tl_wdr3600_kbyte_sec_received
                    name: Kilobytes/second
                  - entity: sensor.wireless_router_tl_wdr3600_bytes_received
                    name: Total Bytes
                  - entity: sensor.wireless_router_tl_wdr3600_packets_sec_received
                    name: Packets/second
                  - entity: sensor.wireless_router_tl_wdr3600_packets_received
                    name: Total Packets
  - title: Lights
    path: lights
    icon: mdi:ceiling-light-outline
    badges: []
    cards:
      - type: light
        entity: light.master_bedroom_lights
      - type: light
        entity: light.living_room_lights
      - type: light
        entity: light.jordan_lamp
      - type: light
        entity: light.wiz_rachel_lamp
      - type: light
        entity: light.bedroom_light_1
      - type: light
        entity: light.bedroom_light_2
  - title: weather
    path: weather
    icon: mdi:weather-sunny-alert
    badges: []
    cards:
      - show_current: true
        show_forecast: true
        type: weather-forecast
        entity: weather.openweathermap
        name: weather
  - title: 1st Floor
    path: 1st-floor
    icon: mdi:floor-plan
    badges: []
    cards: []
  - title: 2nd Floor
    path: 2nd-floor
    icon: mdi:stairs-up
    badges: []
    cards:
      - type: entities
        entities:
          - entity: camera.camera_1_camera_1
        title: camera
      - camera_view: auto
        type: picture-glance
        entities: []
        camera_image: camera.camera_1_camera_1
        title: camera
  - title: Cameras
    path: cameras
    icon: mdi:cctv
    badges: []
    cards:
      - show_state: true
        show_name: true
        camera_view: auto
        type: picture-entity
        entity: camera.camera_1_camera_1
        name: Camera-1
        camera_image: camera.camera_1_camera_1
      - show_state: true
        show_name: true
        camera_view: live
        type: picture-entity
        entity: camera.camera_2_camera_2
        name: Camera-2
        camera_image: camera.camera_2_camera_2
      - show_state: true
        show_name: true
        camera_view: live
        type: picture-entity
        entity: camera.camera_3_camera_3
        name: Camera-3
        camera_image: camera.camera_3_camera_3
      - show_state: true
        show_name: true
        camera_view: live
        type: picture-entity
        entity: camera.front_door
        camera_image: camera.front_door
        aspect_ratio: '16:9'
  - title: Media
    path: media
    icon: mdi:television-play
    badges: []
    cards: []
